language: ruby
cache: bundler
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d64698d96c4ffd988648
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

rvm:
  - 2.1.1

script:
  - bundle install
